### PR TITLE
v1.0.2

### PR DESCRIPTION
**Pull request by marcelosomers**
## Enhancements
- [x] Generate all required files/folders on first build (#20)
- [x] Make `sass_globbing` output a different file than `sass/less/autoprefixer` tasks all watch (#19)
- [x] Allow user to configure the name of the css file that will be watched by the `sass/less/autoprefixer` tasks (#19)
- [x] Migrate from autoprefixer to PostCSS + Autoprefixer plugin (#23)
- [x] Allow user to configure the autoprefixer options (#17)
- [x] Create an Assemble helper for the custom CSS file name
- [x] Create an Assemble helper to allow the user to pass in a custom logo to the default theme
- [x] Support direct execution of the PatternPack grunt task
- [x] Lock down theme to v1.0.0 final
## Bugfixes
- [x] Lock down npm dependency versions (#24)
- [x] Remove additional css file generation (#29)
- [x] Fix duplicate Builds on Release (#30)
- [x] Find issue with `grunt watch` stopping on a new, blank project

### CODE REVIEW

**Comment by marcelosomers** [comment]
Pushed version v1.0.2-beta to npm for testing

**Comment by marcelosomers** [comment]
@johngully I think I found the issue with `grunt:watch` shutting down: A missing "master" Sass file (i.e., `patterns.scss` or whatever you configure in `options.css.fileName`). Once it gets added, it seems to run `grunt:watch` fine.

Given that this is a "breaking" issue, what if we were to add a test during the initial build that verifies the presence of that file. This might lay the ground work for automatically generating the files in the future.

Is basic `node.fs` the best way to do this or can you think of a different way? I know `node.fs` has simple commands to check if a file exists in the file system.

**Comment by johngully** [comment]
I think we are ready to release this!

**Comment by marcelosomers** [comment]
Aww yeeah

Aw Yeah

**Pull request merged**
